name: leaff_app
description: Low carbon footprint app
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.1.6
  flutter_local_notifications: ^16.2.0
  provider: ^6.1.1
  xml2json: ^6.2.7
  intl: ^0.19.0
  shared_preferences: ^2.3.3
  dart_rss: ^3.0.3
  flutter_widget_from_html: ^0.10.0+1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/fonts/
    - assets/images/

  # Fonts
  fonts:
    - family: Instrument Sans
      fonts:
        - asset: assets/fonts/InstrumentSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/InstrumentSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/InstrumentSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/InstrumentSans-Bold.ttf
          weight: 700
