name: leaff_app
description: Application bas carbone inspirée de Finary
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.1.6
  flutter_local_notifications: ^16.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/fonts/

  # Fonts
  fonts:
    - family: Instrument Sans
      fonts:
        - asset: assets/fonts/InstrumentSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/InstrumentSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/InstrumentSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/InstrumentSans-Bold.ttf
          weight: 700
