name: leaff_app
description: Low carbon footprint app
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  cupertino_icons: ^1.0.2
  http: ^1.2.1
  firebase_core: ^3.13.1 # MÀJ pour compatibilité avec firestore et auth modernes
  firebase_auth: ^5.5.4 # Downgrade pour compatibilité avec firebase_core ^2.31.0
  cloud_firestore: ^5.6.8 # Ajout de cloud_firestore
  google_sign_in: ^6.3.0
  flutter_local_notifications: ^16.2.0
  provider: ^6.1.1
  xml2json: ^6.2.7
  intl: ^0.19.0
  shared_preferences: ^2.3.3
  dart_rss: ^3.0.3
  flutter_widget_from_html: ^0.10.0+1
  url_launcher: ^6.3.1
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  uuid: ^4.3.3 # Mis à jour pour générer des identifiants uniques (state)
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  intl_phone_number_input: ^0.7.4
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  dio: ^5.4.0
  app_links: ^3.4.1 # Remplacé uni_links pour une meilleure maintenance
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  build_runner: ^2.4.6
  google_fonts: ^6.1.0 # Pour la gestion des polices Google Fonts

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

  flutter_lints: ^4.0.0 # Ajout pour les règles de linting recommandées

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/fonts/
    - assets/images/
    - .env

  # Fonts
  fonts:
    - family: Instrument Sans
      fonts:
        - asset: assets/fonts/InstrumentSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/InstrumentSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/InstrumentSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/InstrumentSans-Bold.ttf
          weight: 700
